/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.veterinaria.View;

import java.awt.event.ActionListener;

/**
 *
 * @author Stephanie
 */
public class DataPanelButtons extends javax.swing.JPanel {

    /**
     * Creates new form DataPanelButtons
     */
    public DataPanelButtons() {
        initComponents();
    }
    
    public void listen(ActionListener controller){
        this.btnAdd.addActionListener(controller);
        this.btnEdit.addActionListener(controller);
        this.btnReport.addActionListener(controller);
        this.btnDelete.addActionListener(controller);
        this.btnExit.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8664789_circle_check_mark_accept_icon.png"))); // NOI18N
        btnAdd.setActionCommand("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8664843_pen_to_square_icon.png"))); // NOI18N
        btnEdit.setActionCommand("Edit");

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8664938_trash_can_delete_remove_icon.png"))); // NOI18N
        btnDelete.setActionCommand("Delete");

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8664851_circle_xmark_icon.png"))); // NOI18N
        btnExit.setActionCommand("Exit");

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8664805_chart_bar_icon.png"))); // NOI18N
        btnReport.setActionCommand("Report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd)
                    .addComponent(btnReport)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReport;
    // End of variables declaration//GEN-END:variables
}
